#!/usr/bin/python
import sys
range_limit=int(open(sys.argv[1]).read().strip())
for num in range(1, range_limit+1):
    if num%3==0 and num%5==0:
        print 'Hop'
    elif num%3==0:
        print 'Hoppity'
    elif num%5==0:
        print 'Hophop'