'''
Problem 2


Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
'''

from utils import fibonacci
import sys


try:
    num = int(sys.argv[1])
except:
    num = 4000000


f = fibonacci()
answer = 0
for i in f:
    if i > num:
        break
    elif i % 2 == 0:
        answer += i

print(answer)
