'''
Problem 2


Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
'''

from mathkit import Fibonacci

def ex2(num=4000000):
    f=Fibonacci()
    r=0
    while True:
        next=f.next()
        if next>num:
            break
        elif next%2==0:
            r+=next
    return r

if __name__ == "__main__":
    print ex2()